name: CI

on:
  push:
    paths:
      - 'species/**.txt'

jobs:
  data-integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        # docker hub image
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          repository: nordicmicroalgae/backend
          path: backend

      - name: Checkout content
        uses: actions/checkout@v4
        with:
          repository: nordicmicroalgae/content
          path: shared/content

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r backend/requirements.txt

      - name: Setup and populate database
        run: |
          python backend/manage.py migrate -v 0
          python backend/manage.py importtaxa -v 2
          python backend/manage.py importsynonyms -v 2
          python backend/manage.py importfacts -v 2
        env:
          DJANGO_DATABASE_NAME: postgres
          DJANGO_DATABASE_USER: postgres
          DJANGO_DATABASE_PASSWORD: postgres
